services:
  service:
    build:
      context: .
    environment:
      LOGGING_CONFIG_LEVEL: "${LOGGING_CONFIG_LEVEL:-DEBUG}"
      LOGGING_CONFIG_NAMESPACES: '${LOGGING_CONFIG_NAMESPACES:-["", "uvicorn"]}'
      O_AUTH2_CLIENT_TYPE: "${O_AUTH2_CLIENT_TYPE:-}"
      O_AUTH2_CLIENT_STANDARD_CONFIG_CLIENT_ID: "${O_AUTH2_CLIENT_STANDARD_CONFIG_CLIENT_ID:-}"
      O_AUTH2_CLIENT_STANDARD_CONFIG_CLIENT_SECRET: "${O_AUTH2_CLIENT_STANDARD_CONFIG_CLIENT_SECRET:-}"
      O_AUTH2_CLIENT_STANDARD_CONFIG_REDIRECT_URI: "${O_AUTH2_CLIENT_STANDARD_CONFIG_REDIRECT_URI:-}"
      O_AUTH2_CLIENT_STANDARD_CONFIG_AUTHORIZE_URL: "${O_AUTH2_CLIENT_STANDARD_CONFIG_AUTHORIZE_URL:-}"
      O_AUTH2_CLIENT_STANDARD_CONFIG_TOKEN_URL: "${O_AUTH2_CLIENT_STANDARD_CONFIG_TOKEN_URL:-}"
      CACHE_TYPE: "${CACHE_TYPE:-}"
      CACHE_NAMESPACE_NAMESPACE: "${CACHE_NAMESPACE_NAMESPACE:-}"
    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
    ports:
      - "8000:80"
